import { storagePut } from "./storage";
import type { Strategy } from "../drizzle/schema";
import { nanoid } from "nanoid";

/**
 * Export service for generating PDFs and shareable links from strategies
 */

const MODULE_NAMES = {
  executiveBrief: "Executive CMO Brief",
  marketPositioning: "Market Positioning",
  growthStrategy: "Growth Strategy",
  funnelArchitecture: "Funnel Architecture",
  contentMessaging: "Content & Messaging",
  executionRoadmap: "Execution Roadmap",
  toolRecommendations: "Tool & AI Stack Recommendations",
};

/**
 * Generate a simple HTML document from strategy
 */
function generateHTML(strategy: Strategy, businessName: string): string {
  const modules = [
    { key: "executiveBrief", name: MODULE_NAMES.executiveBrief, content: strategy.executiveBrief },
    { key: "marketPositioning", name: MODULE_NAMES.marketPositioning, content: strategy.marketPositioning },
    { key: "growthStrategy", name: MODULE_NAMES.growthStrategy, content: strategy.growthStrategy },
    { key: "funnelArchitecture", name: MODULE_NAMES.funnelArchitecture, content: strategy.funnelArchitecture },
    { key: "contentMessaging", name: MODULE_NAMES.contentMessaging, content: strategy.contentMessaging },
    { key: "executionRoadmap", name: MODULE_NAMES.executionRoadmap, content: strategy.executionRoadmap },
    { key: "toolRecommendations", name: MODULE_NAMES.toolRecommendations, content: strategy.toolRecommendations },
  ];

  const modulesHTML = modules
    .filter((m) => m.content)
    .map(
      (m) => `
      <div class="module">
        <h2>${m.name}</h2>
        <div class="content">${(m.content || "").replace(/\n/g, "<br>")}</div>
      </div>
    `
    )
    .join("");

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Marketing Strategy - ${businessName}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      background: #ffffff;
      padding: 40px 20px;
    }
    
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    
    .header {
      text-align: center;
      margin-bottom: 60px;
      padding-bottom: 30px;
      border-bottom: 3px solid #3b82f6;
    }
    
    .header h1 {
      font-size: 36px;
      font-weight: 700;
      color: #1a1a1a;
      margin-bottom: 10px;
    }
    
    .header .subtitle {
      font-size: 18px;
      color: #6b7280;
    }
    
    .module {
      margin-bottom: 50px;
      page-break-inside: avoid;
    }
    
    .module h2 {
      font-size: 24px;
      font-weight: 600;
      color: #3b82f6;
      margin-bottom: 20px;
      padding-bottom: 10px;
      border-bottom: 2px solid #e5e7eb;
    }
    
    .module .content {
      font-size: 15px;
      line-height: 1.8;
      color: #374151;
    }
    
    .module .content strong {
      color: #1a1a1a;
      font-weight: 600;
    }
    
    .footer {
      margin-top: 60px;
      padding-top: 30px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 14px;
    }
    
    @media print {
      body {
        padding: 20px;
      }
      
      .module {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Marketing Strategy</h1>
      <div class="subtitle">${businessName}</div>
      <div class="subtitle" style="font-size: 14px; margin-top: 10px;">
        Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </div>
    </div>
    
    ${modulesHTML}
    
    <div class="footer">
      Generated by Taptico AI - Elite Marketing Strategy Platform
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * Export strategy as PDF (stored in S3)
 */
export async function exportToPDF(strategy: Strategy, businessName: string): Promise<string> {
  const html = generateHTML(strategy, businessName);
  
  // Generate a unique filename
  const filename = `strategy-${strategy.id}-${nanoid(8)}.html`;
  
  // Upload HTML to S3 (can be converted to PDF on the frontend or via a service)
  const { url } = await storagePut(
    `exports/${filename}`,
    Buffer.from(html, "utf-8"),
    "text/html"
  );
  
  return url;
}

/**
 * Generate a shareable link token
 */
export function generateShareToken(): string {
  return nanoid(32);
}
